# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_APP_VALUE_LEN "1")
set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/donghyeon/openvino_andrew;/home/donghyeon/openvino_andrew/build_debug")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "ngraph;gpu;gna;hetero;multi;tbb;core;cpp_samples;c_samples;model_optimizer;setupvars;install_dependencies;demo_scripts")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEMO_SCRIPTS_DEPENDS "core")
set(CPACK_COMPONENT_DEMO_SCRIPTS_DISABLED "FALSE")
set(CPACK_COMPONENT_DEMO_SCRIPTS_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_DEMO_SCRIPTS_HIDDEN "FALSE")
set(CPACK_COMPONENT_DEMO_SCRIPTS_REQUIRED "TRUE")
set(CPACK_COMPONENT_INSTALL_DEPENDENCIES_DISABLED "FALSE")
set(CPACK_COMPONENT_INSTALL_DEPENDENCIES_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_INSTALL_DEPENDENCIES_HIDDEN "FALSE")
set(CPACK_COMPONENT_INSTALL_DEPENDENCIES_REQUIRED "TRUE")
set(CPACK_COMPONENT_SETUPVARS_DISABLED "FALSE")
set(CPACK_COMPONENT_SETUPVARS_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_SETUPVARS_HIDDEN "FALSE")
set(CPACK_COMPONENT_SETUPVARS_REQUIRED "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "OpenVINO built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/donghyeon/openvino_andrew/build_debug;OpenVINO;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "inference-engine custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "inference-engine custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/donghyeon/openvino_andrew/build_debug/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenVINO built using CMake")
set(CPACK_PACKAGE_FILE_NAME "inference-engine-custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "inference-engine custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "inference-engine custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad")
set(CPACK_PACKAGE_NAME "inference-engine")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Intel")
set(CPACK_PACKAGE_VERSION "custom_andrew_async_batch_test_dfc0c0d327eeef3d2f7d982fcfbd7e2d1984d5ad")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/local/share/cmake-3.17/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.17/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/donghyeon/openvino_andrew/build_debug/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "ON")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/donghyeon/openvino_andrew/build_debug/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
