# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget IE::ie_tests IE::funcTestUtils IE::ieTestHelpers IE::ieTestHelpers_s IE::IESharedTests IE::IEBehaviorSharedTests IE::ngraphFunctions IE::lptNgraphFunctions IE::commonTestUtils IE::gtest IE::gtest_main IE::commonTestUtils_s IE::unitTestUtils IE::inference_engine_s IE::gmock IE::sharedTestClasses IE::funcSharedTests)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target IE::ie_tests
add_library(IE::ie_tests STATIC IMPORTED)

set_target_properties(IE::ie_tests PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/ie_tests/include"
  INTERFACE_LINK_LIBRARIES "IE::format_reader;IE::funcTestUtils;IE::ieTestHelpers"
)

# Create imported target IE::funcTestUtils
add_library(IE::funcTestUtils STATIC IMPORTED)

set_target_properties(IE::funcTestUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils/functional_test_utils/include;\$<TARGET_PROPERTY:IE::inference_engine_plugin_api,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "IE::commonTestUtils;IE::inference_engine_transformations;IE::inference_engine_lp_transformations;IE::inference_engine;IE::inference_engine_legacy"
)

# Create imported target IE::ieTestHelpers
add_library(IE::ieTestHelpers STATIC IMPORTED)

set_target_properties(IE::ieTestHelpers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/helpers;/home/donghyeon/openvino_andrew/inference-engine/src/inference_engine;\$<TARGET_PROPERTY:IE::pugixml,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/openvino_andrew/inference-engine/src/vpu/;/home/donghyeon/openvino_andrew/inference-engine/src/plugin_api;/home/donghyeon/openvino_andrew/inference-engine/src/legacy_api/include;/home/donghyeon/openvino_andrew/inference-engine/samples/common/os/windows"
  INTERFACE_LINK_LIBRARIES "IE::commonTestUtils"
)

# Create imported target IE::ieTestHelpers_s
add_library(IE::ieTestHelpers_s STATIC IMPORTED)

set_target_properties(IE::ieTestHelpers_s PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/helpers;/home/donghyeon/openvino_andrew/inference-engine/src/inference_engine;\$<TARGET_PROPERTY:IE::pugixml,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/openvino_andrew/inference-engine/src/vpu/;/home/donghyeon/openvino_andrew/inference-engine/src/plugin_api;/home/donghyeon/openvino_andrew/inference-engine/src/legacy_api/include;/home/donghyeon/openvino_andrew/inference-engine/samples/common/os/windows"
  INTERFACE_LINK_LIBRARIES "IE::commonTestUtils_s"
)

# Create imported target IE::IESharedTests
add_library(IE::IESharedTests STATIC IMPORTED)

set_target_properties(IE::IESharedTests PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USE_OPENCV"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/io_blob_tests;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/input_tests;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/inference_engine_regression_tests;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/lstm;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/common_single_layer_tests;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/single_layer_tests;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/functional/shared_tests/graph_tools;\$<TARGET_PROPERTY:IE::inference_engine_plugin_api,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/intel/openvino_2021.2.185/opencv/include"
  INTERFACE_LINK_LIBRARIES "IE::ngraph;IE::ie_tests;IE::ngraphFunctions;opencv_imgcodecs;opencv_imgproc"
)

# Create imported target IE::IEBehaviorSharedTests
add_library(IE::IEBehaviorSharedTests STATIC IMPORTED)

set_target_properties(IE::IEBehaviorSharedTests PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/behavior/shared_tests/plugin_tests;/home/donghyeon/openvino_andrew/inference-engine/src/vpu/graph_transformer/include;\$<TARGET_PROPERTY:IE::inference_engine_plugin_api,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/openvino_andrew/inference-engine/tests_deprecated/behavior/shared_tests/plugin_tests"
  INTERFACE_LINK_LIBRARIES "IE::funcTestUtils;IE::ieTestHelpers;\$<LINK_ONLY:Threads::Threads>;IE::gmock"
)

# Create imported target IE::ngraphFunctions
add_library(IE::ngraphFunctions STATIC IMPORTED)

set_target_properties(IE::ngraphFunctions PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ngraph_helpers/ngraph_functions/include"
  INTERFACE_LINK_LIBRARIES "IE::ngraph;IE::ngraph_backend;IE::interpreter_backend"
)

# Create imported target IE::lptNgraphFunctions
add_library(IE::lptNgraphFunctions STATIC IMPORTED)

set_target_properties(IE::lptNgraphFunctions PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:IE::ngraphFunctions>;\$<LINK_ONLY:IE::inference_engine_lp_transformations>;\$<LINK_ONLY:IE::inference_engine_legacy>"
)

# Create imported target IE::commonTestUtils
add_library(IE::commonTestUtils STATIC IMPORTED)

set_target_properties(IE::commonTestUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils;\$<TARGET_PROPERTY:IE::inference_engine,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::inference_engine_legacy,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::pugixml,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "IE::pugixml;IE::ngraph;IE::gtest;IE::gtest_main"
)

# Create imported target IE::gtest
add_library(IE::gtest STATIC IMPORTED)

set_target_properties(IE::gtest PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils/common_test_utils/gtest/googletest/include"
)

# Create imported target IE::gtest_main
add_library(IE::gtest_main STATIC IMPORTED)

set_target_properties(IE::gtest_main PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils/common_test_utils/gtest/googletest/include"
)

# Create imported target IE::commonTestUtils_s
add_library(IE::commonTestUtils_s STATIC IMPORTED)

set_target_properties(IE::commonTestUtils_s PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USE_STATIC_IE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils;\$<TARGET_PROPERTY:IE::inference_engine,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::inference_engine_legacy,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::pugixml,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "IE::pugixml;IE::ngraph;IE::gtest;IE::gtest_main"
)

# Create imported target IE::unitTestUtils
add_library(IE::unitTestUtils STATIC IMPORTED)

set_target_properties(IE::unitTestUtils PROPERTIES
  INTERFACE_LINK_LIBRARIES "IE::commonTestUtils_s;IE::inference_engine_s;IE::gmock"
)

# Create imported target IE::inference_engine_s
add_library(IE::inference_engine_s STATIC IMPORTED)

set_target_properties(IE::inference_engine_s PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB;USE_STATIC_IE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/src/inference_engine;\$<TARGET_PROPERTY:IE::inference_engine_plugin_api,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/openvino_andrew/inference-engine/src/legacy_api/src"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;TBB::tbbmalloc;-pthread;\$<LINK_ONLY:IE::itt>;\$<LINK_ONLY:dl>;\$<LINK_ONLY:IE::ngraph>;\$<LINK_ONLY:IE::inference_engine_transformations>;\$<LINK_ONLY:IE::pugixml>"
)

# Create imported target IE::gmock
add_library(IE::gmock STATIC IMPORTED)

set_target_properties(IE::gmock PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/ie_test_utils/common_test_utils/gtest/googlemock/include"
)

# Create imported target IE::sharedTestClasses
add_library(IE::sharedTestClasses STATIC IMPORTED)

set_target_properties(IE::sharedTestClasses PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/functional/shared_test_classes/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:IE::funcTestUtils>;\$<LINK_ONLY:IE::ngraphFunctions>"
)

# Create imported target IE::funcSharedTests
add_library(IE::funcSharedTests STATIC IMPORTED)

set_target_properties(IE::funcSharedTests PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/tests/functional/plugin/shared/include"
  INTERFACE_LINK_LIBRARIES "IE::funcTestUtils;IE::ngraphFunctions;IE::lptNgraphFunctions;IE::sharedTestClasses;\$<LINK_ONLY:IE::inference_engine_transformations>"
)

# Import target "IE::ie_tests" for configuration "Debug"
set_property(TARGET IE::ie_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::ie_tests PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libie_tests.a"
  )

# Import target "IE::funcTestUtils" for configuration "Debug"
set_property(TARGET IE::funcTestUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::funcTestUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libfuncTestUtils.a"
  )

# Import target "IE::ieTestHelpers" for configuration "Debug"
set_property(TARGET IE::ieTestHelpers APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::ieTestHelpers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libieTestHelpers.a"
  )

# Import target "IE::ieTestHelpers_s" for configuration "Debug"
set_property(TARGET IE::ieTestHelpers_s APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::ieTestHelpers_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libieTestHelpers_s.a"
  )

# Import target "IE::IESharedTests" for configuration "Debug"
set_property(TARGET IE::IESharedTests APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::IESharedTests PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libIESharedTests.a"
  )

# Import target "IE::IEBehaviorSharedTests" for configuration "Debug"
set_property(TARGET IE::IEBehaviorSharedTests APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::IEBehaviorSharedTests PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libIEBehaviorSharedTests.a"
  )

# Import target "IE::ngraphFunctions" for configuration "Debug"
set_property(TARGET IE::ngraphFunctions APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::ngraphFunctions PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libngraphFunctions.a"
  )

# Import target "IE::lptNgraphFunctions" for configuration "Debug"
set_property(TARGET IE::lptNgraphFunctions APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::lptNgraphFunctions PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/liblptNgraphFunctions.a"
  )

# Import target "IE::commonTestUtils" for configuration "Debug"
set_property(TARGET IE::commonTestUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::commonTestUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libcommonTestUtils.a"
  )

# Import target "IE::gtest" for configuration "Debug"
set_property(TARGET IE::gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "-pthread"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libgtest.a"
  )

# Import target "IE::gtest_main" for configuration "Debug"
set_property(TARGET IE::gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "-pthread;IE::gtest"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libgtest_main.a"
  )

# Import target "IE::commonTestUtils_s" for configuration "Debug"
set_property(TARGET IE::commonTestUtils_s APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::commonTestUtils_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libcommonTestUtils_s.a"
  )

# Import target "IE::unitTestUtils" for configuration "Debug"
set_property(TARGET IE::unitTestUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::unitTestUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libunitTestUtils.a"
  )

# Import target "IE::inference_engine_s" for configuration "Debug"
set_property(TARGET IE::inference_engine_s APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::inference_engine_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libinference_engine_s.a"
  )

# Import target "IE::gmock" for configuration "Debug"
set_property(TARGET IE::gmock APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::gmock PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "-pthread"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libgmock.a"
  )

# Import target "IE::sharedTestClasses" for configuration "Debug"
set_property(TARGET IE::sharedTestClasses APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::sharedTestClasses PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libsharedTestClasses.a"
  )

# Import target "IE::funcSharedTests" for configuration "Debug"
set_property(TARGET IE::funcSharedTests APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::funcSharedTests PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libfuncSharedTests.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
