# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget IE::xbyak IE::itt IE::conditional_compilation IE::ade IE::fluid IE::pugixml IE::format_reader)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target IE::xbyak
add_library(IE::xbyak INTERFACE IMPORTED)

set_target_properties(IE::xbyak PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/thirdparty/xbyak"
)

# Create imported target IE::itt
add_library(IE::itt STATIC IMPORTED)

set_target_properties(IE::itt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/openvino/itt/include"
)

# Create imported target IE::conditional_compilation
add_library(IE::conditional_compilation INTERFACE IMPORTED)

set_target_properties(IE::conditional_compilation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/openvino/conditional_compilation/include"
  INTERFACE_LINK_LIBRARIES "IE::itt"
)

# Create imported target IE::ade
add_library(IE::ade STATIC IMPORTED)

set_target_properties(IE::ade PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/thirdparty/ade/sources/ade/include"
)

# Create imported target IE::fluid
add_library(IE::fluid STATIC IMPORTED)

set_target_properties(IE::fluid PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GAPI_STANDALONE;cv=fluidcv"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/thirdparty/fluid/modules/gapi/cmake/..//include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:IE::ade>"
)

# Create imported target IE::pugixml
add_library(IE::pugixml STATIC IMPORTED)

set_target_properties(IE::pugixml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_long_long_type"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/thirdparty/pugixml/src"
)

# Create imported target IE::format_reader
add_library(IE::format_reader SHARED IMPORTED)

set_target_properties(IE::format_reader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/samples/common/format_reader;/home/donghyeon/openvino_andrew/inference-engine/samples/common/format_reader/.."
  INTERFACE_LINK_LIBRARIES "-Wl,-rpath-link,/home/donghyeon/intel/openvino_2021.2.185/opencv/lib"
)

# Import target "IE::itt" for configuration "Debug"
set_property(TARGET IE::itt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::itt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libitt.a"
  )

# Import target "IE::ade" for configuration "Debug"
set_property(TARGET IE::ade APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::ade PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/build_debug/lib/libade.a"
  )

# Import target "IE::fluid" for configuration "Debug"
set_property(TARGET IE::fluid APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::fluid PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libfluid.a"
  )

# Import target "IE::pugixml" for configuration "Debug"
set_property(TARGET IE::pugixml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::pugixml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libpugixml.a"
  )

# Import target "IE::format_reader" for configuration "Debug"
set_property(TARGET IE::format_reader APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(IE::format_reader PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "opencv_imgcodecs;opencv_videoio;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "/home/donghyeon/openvino_andrew/bin/intel64/Debug/lib/libformat_reader.so"
  IMPORTED_SONAME_DEBUG "libformat_reader.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
