# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget IE::vpu_common_lib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target IE::vpu_common_lib
add_library(IE::vpu_common_lib STATIC IMPORTED)

set_target_properties(IE::vpu_common_lib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/src/vpu/common/include;\$<TARGET_PROPERTY:IE::ngraph,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::inference_engine_plugin_api,INTERFACE_INCLUDE_DIRECTORIES>;\$<TARGET_PROPERTY:IE::inference_engine_legacy,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;TBB::tbbmalloc;-pthread;IE::ngraph;IE::inference_engine_transformations;\$<LINK_ONLY:IE::itt>;IE::inference_engine_legacy"
)

# Import target "IE::vpu_common_lib" for configuration "Release"
set_property(TARGET IE::vpu_common_lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::vpu_common_lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libvpu_common_lib.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
