# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget IE::inference_engine_preproc IE::inference_engine_legacy IE::inference_engine_transformations IE::inference_engine IE::inference_engine_plugin_api IE::inference_engine_lp_transformations IE::offline_transformations)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target IE::inference_engine_preproc
add_library(IE::inference_engine_preproc MODULE IMPORTED)

set_target_properties(IE::inference_engine_preproc PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/src/preprocessing"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;TBB::tbbmalloc;-pthread;IE::inference_engine"
)

# Create imported target IE::inference_engine_legacy
add_library(IE::inference_engine_legacy SHARED IMPORTED)

set_target_properties(IE::inference_engine_legacy PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/src/legacy_api/include"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;TBB::tbbmalloc;-pthread;IE::inference_engine"
)

# Create imported target IE::inference_engine_transformations
add_library(IE::inference_engine_transformations SHARED IMPORTED)

set_target_properties(IE::inference_engine_transformations PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/src/transformations/include"
  INTERFACE_LINK_LIBRARIES "IE::ngraph"
)

# Create imported target IE::inference_engine
add_library(IE::inference_engine SHARED IMPORTED)

set_target_properties(IE::inference_engine PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/include"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;TBB::tbbmalloc;-pthread"
)

# Create imported target IE::inference_engine_plugin_api
add_library(IE::inference_engine_plugin_api INTERFACE IMPORTED)

set_target_properties(IE::inference_engine_plugin_api PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IE_THREAD=IE_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/temp/tbb/include;/home/donghyeon/openvino_andrew/inference-engine/src/plugin_api;\$<TARGET_PROPERTY:IE::inference_engine_preproc,INTERFACE_INCLUDE_DIRECTORIES>;/home/donghyeon/openvino_andrew/inference-engine/include"
  INTERFACE_LINK_LIBRARIES "IE::itt;IE::conditional_compilation;TBB::tbb;TBB::tbbmalloc;-pthread"
)

# Create imported target IE::inference_engine_lp_transformations
add_library(IE::inference_engine_lp_transformations SHARED IMPORTED)

set_target_properties(IE::inference_engine_lp_transformations PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/src/low_precision_transformations/include"
  INTERFACE_LINK_LIBRARIES "IE::inference_engine_transformations"
)

# Create imported target IE::offline_transformations
add_library(IE::offline_transformations STATIC IMPORTED)

set_target_properties(IE::offline_transformations PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/inference-engine/src/offline_transformations/include"
  INTERFACE_LINK_LIBRARIES "IE::ngraph;IE::inference_engine_transformations;\$<LINK_ONLY:IE::itt>"
)

# Import target "IE::inference_engine_preproc" for configuration "Release"
set_property(TARGET IE::inference_engine_preproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::inference_engine_preproc PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinference_engine_preproc.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# Import target "IE::inference_engine_legacy" for configuration "Release"
set_property(TARGET IE::inference_engine_legacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::inference_engine_legacy PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "IE::ngraph;IE::inference_engine_transformations"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinference_engine_legacy.so"
  IMPORTED_SONAME_RELEASE "libinference_engine_legacy.so"
  )

# Import target "IE::inference_engine_transformations" for configuration "Release"
set_property(TARGET IE::inference_engine_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::inference_engine_transformations PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinference_engine_transformations.so"
  IMPORTED_SONAME_RELEASE "libinference_engine_transformations.so"
  )

# Import target "IE::inference_engine" for configuration "Release"
set_property(TARGET IE::inference_engine APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::inference_engine PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "IE::ngraph;IE::inference_engine_transformations"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinference_engine.so"
  IMPORTED_SONAME_RELEASE "libinference_engine.so"
  )

# Import target "IE::inference_engine_lp_transformations" for configuration "Release"
set_property(TARGET IE::inference_engine_lp_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::inference_engine_lp_transformations PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinference_engine_lp_transformations.so"
  IMPORTED_SONAME_RELEASE "libinference_engine_lp_transformations.so"
  )

# Import target "IE::offline_transformations" for configuration "Release"
set_property(TARGET IE::offline_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::offline_transformations PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/liboffline_transformations.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
