# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget IE::ngraph_builders IE::ngraph_reference IE::ngraph IE::ngraph_backend IE::interpreter_backend)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target IE::ngraph_builders
add_library(IE::ngraph_builders STATIC IMPORTED)

set_target_properties(IE::ngraph_builders PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/ngraph/core/builder/include/"
)

# Create imported target IE::ngraph_reference
add_library(IE::ngraph_reference STATIC IMPORTED)

set_target_properties(IE::ngraph_reference PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/ngraph/core/reference/include;/home/donghyeon/openvino_andrew/ngraph/core/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:IE::xbyak>"
)

# Create imported target IE::ngraph
add_library(IE::ngraph SHARED IMPORTED)

set_target_properties(IE::ngraph PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/ngraph/core/include"
)

# Create imported target IE::ngraph_backend
add_library(IE::ngraph_backend SHARED IMPORTED)

set_target_properties(IE::ngraph_backend PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/donghyeon/openvino_andrew/ngraph/test/runtime"
  INTERFACE_LINK_LIBRARIES "IE::ngraph;IE::ngraph_builders;IE::ngraph_reference"
)

# Create imported target IE::interpreter_backend
add_library(IE::interpreter_backend SHARED IMPORTED)

set_target_properties(IE::interpreter_backend PROPERTIES
  INTERFACE_LINK_LIBRARIES "IE::ngraph_backend"
)

# Import target "IE::ngraph_builders" for configuration "Release"
set_property(TARGET IE::ngraph_builders APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::ngraph_builders PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libngraph_builders.a"
  )

# Import target "IE::ngraph_reference" for configuration "Release"
set_property(TARGET IE::ngraph_reference APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::ngraph_reference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libngraph_reference.a"
  )

# Import target "IE::ngraph" for configuration "Release"
set_property(TARGET IE::ngraph APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::ngraph PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libngraph.so"
  IMPORTED_SONAME_RELEASE "libngraph.so"
  )

# Import target "IE::ngraph_backend" for configuration "Release"
set_property(TARGET IE::ngraph_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::ngraph_backend PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libngraph_backend.so"
  IMPORTED_SONAME_RELEASE "libngraph_backend.so"
  )

# Import target "IE::interpreter_backend" for configuration "Release"
set_property(TARGET IE::interpreter_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IE::interpreter_backend PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/donghyeon/openvino_andrew/bin/intel64/Release/lib/libinterpreter_backend.so"
  IMPORTED_SONAME_RELEASE "libinterpreter_backend.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
